# Generated by Django 4.1.7 on 2023-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.TextField(blank=True, null=True)),
                ("field2", models.TextField(blank=True, null=True)),
                ("field3", models.TextField(blank=True, null=True)),
                ("field4", models.TextField(blank=True, null=True)),
                ("field5", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "clima",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Consumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.TextField(blank=True, null=True)),
                ("field2", models.TextField(blank=True, null=True)),
                ("field3", models.TextField(blank=True, null=True)),
                ("field4", models.TextField(blank=True, null=True)),
                ("field5", models.TextField(blank=True, null=True)),
                ("field6", models.TextField(blank=True, null=True)),
                ("field7", models.TextField(blank=True, null=True)),
                ("field8", models.TextField(blank=True, null=True)),
                ("field9", models.TextField(blank=True, null=True)),
                ("field10", models.TextField(blank=True, null=True)),
                ("field11", models.TextField(blank=True, null=True)),
                ("field12", models.TextField(blank=True, null=True)),
                ("field13", models.TextField(blank=True, null=True)),
                ("field14", models.TextField(blank=True, null=True)),
                ("field15", models.TextField(blank=True, null=True)),
                ("field16", models.TextField(blank=True, null=True)),
                ("field17", models.TextField(blank=True, null=True)),
                ("field18", models.TextField(blank=True, null=True)),
                ("field19", models.TextField(blank=True, null=True)),
                ("field20", models.TextField(blank=True, null=True)),
                ("field21", models.TextField(blank=True, null=True)),
                ("field22", models.TextField(blank=True, null=True)),
                ("field23", models.TextField(blank=True, null=True)),
                ("field24", models.TextField(blank=True, null=True)),
                ("field25", models.TextField(blank=True, null=True)),
                ("field26", models.TextField(blank=True, null=True)),
                ("field27", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "consumo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Generacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.TextField(blank=True, null=True)),
                ("field2", models.TextField(blank=True, null=True)),
                ("field3", models.TextField(blank=True, null=True)),
                ("field4", models.TextField(blank=True, null=True)),
                ("field5", models.TextField(blank=True, null=True)),
                ("field6", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "generacion",
                "managed": False,
            },
        ),
    ]
